services:
  - type: web
    name: calorie-burn-predictor
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      unzip rfr.zip || echo "ZIP extraction skipped"
    startCommand: streamlit run app.py --server.port=$PORT --server.headless=true --server.enableCORS=false
    envVars:
      - key: PORT
        value: 8080
    plan: free